#!/usr/bin/env python3
"""Build the approved gdTAI V4.2 NK-reference integration sidecar.

The command is stage-addressable and fail-closed. ``validate`` uses the
preflight implementation approval. Every project-data stage additionally
requires the checksum-bound approval generated by implementation QC.
"""

from __future__ import annotations

import argparse
import gc
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
from scipy import sparse

from workflows.gdtai.gdtai_v4_2_integration_core import (
    ROOT,
    apply_current_atlas_recovery,
    attach_recovery_metadata,
    atomic_write_json,
    common_eligible_genes,
    ensure_no_locked_cohorts,
    h5ad_obs_frame,
    h5ad_var_names,
    input_file_state,
    iter_parameter_grid,
    make_integration_batch,
    minimum_free_gib_for_stage,
    mixed_boundary_mask,
    read_json,
    read_sparse_rows_genes,
    recovery_excluded_cell_ids,
    resolve,
    role_contract_sha256,
    sha256_file,
    source_balanced_sample_indices,
    validate_preflight_approval,
    validate_project_data_approval,
    validate_pseudolabel_contract,
    validate_recovery_preflight,
    validate_resource_preflight,
    cluster_consensus_votes,
)


DEFAULT_CONFIG = ROOT / "configs/models/gdtai/v4_2_integration_execution.json"
RUNNER_PATH = Path(__file__).resolve()
CORE_PATH = RUNNER_PATH.with_name("gdtai_v4_2_integration_core.py")
OBS_COLUMNS = [
    "source_gse_id",
    "donor_id",
    "sample_id",
    "library_id",
    "technology_simple",
    "original_cell_id",
    "has_any_ab_tcr",
    "has_any_gd_tcr",
    "has_TRA_TRB_paired",
    "has_TRG_TRD_paired",
    "doublet_flag",
    "predicted_doublet",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--stage",
        choices=["validate", "prepare", "fit", "cluster", "consensus", "all"],
        default="validate",
    )
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def stage_paths(config: dict[str, Any]) -> dict[str, Path]:
    ssd = Path(config["resources"]["ssd_root"])
    outputs = config["outputs"]
    return {
        "ssd": ssd,
        "staged_h5ad": ssd / "development_hvg_counts.h5ad",
        "model": ssd / "scvi_model",
        "latent": ssd / "X_scVI.npy",
        "partitions": ssd / "cluster_partitions.npz",
        "table": resolve(outputs["table_dir"]),
        "figure": resolve(outputs["figure_dir"]),
        "log": resolve(outputs["log_dir"]),
        "static": resolve(outputs["static_dir"]),
    }


def make_direct_cuda_environment() -> dict[str, str]:
    unique_mps = f"/tmp/gdtai-v42-mps-{os.getuid()}-{os.getpid()}"
    inherited = os.environ.get("CUDA_MPS_PIPE_DIRECTORY", "")
    if inherited == "/tmp/nvidia-mps" or (inherited and not inherited.startswith("/tmp/gdtai-v42-mps-")):
        os.environ.pop("CUDA_MPS_PIPE_DIRECTORY", None)
    os.environ.setdefault("CUDA_MPS_PIPE_DIRECTORY", unique_mps)
    os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
    os.environ.setdefault("PYTHONHASHSEED", "20260807")
    return {
        "CUDA_MPS_PIPE_DIRECTORY": os.environ["CUDA_MPS_PIPE_DIRECTORY"],
        "CUDA_VISIBLE_DEVICES": os.environ["CUDA_VISIBLE_DEVICES"],
        "CUBLAS_WORKSPACE_CONFIG": os.environ["CUBLAS_WORKSPACE_CONFIG"],
        "PYTHONHASHSEED": os.environ["PYTHONHASHSEED"],
    }


def require_gpu(config: dict[str, Any]) -> dict[str, Any]:
    environment = make_direct_cuda_environment()
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is unavailable; CPU fallback is forbidden")
    properties = torch.cuda.get_device_properties(0)
    total_gib = properties.total_memory / 2**30
    minimum = float(config["scvi"]["minimum_gpu_memory_gib"])
    if total_gib < minimum:
        raise RuntimeError(f"GPU memory {total_gib:.1f} GiB is below the {minimum:.1f}-GiB contract")
    torch.use_deterministic_algorithms(True, warn_only=False)
    torch.backends.cudnn.benchmark = False
    torch.backends.cuda.matmul.allow_tf32 = False
    return {
        **environment,
        "torch_version": torch.__version__,
        "device_name": properties.name,
        "total_memory_gib": total_gib,
        "cuda_available": True,
    }


def ensure_resources(config: dict[str, Any], paths: dict[str, Path], stage: str) -> dict[str, float]:
    paths["ssd"].mkdir(parents=True, exist_ok=True)
    free_gib = shutil.disk_usage(paths["ssd"]).free / 2**30
    minimum = minimum_free_gib_for_stage(config, stage)
    if free_gib < minimum:
        raise RuntimeError(
            f"SSD free space {free_gib:.1f} GiB is below the {minimum:.1f}-GiB contract for {stage}"
        )
    for key in ["table", "figure", "log", "static"]:
        paths[key].mkdir(parents=True, exist_ok=True)
    return {"observed_free_gib": free_gib, "required_free_gib": minimum}


def development_roles(config: dict[str, Any]) -> pd.DataFrame:
    contract = validate_preflight_approval(config)
    roles = contract["roles"]
    roles = apply_current_atlas_recovery(config, roles)
    selected = roles[roles["include_in_integration_fit"]].copy()
    if selected["allow_locked_evaluation"].any():
        raise RuntimeError("Locked cohort selected for development integration")
    return selected


def verify_input_contract(roles: pd.DataFrame, hash_development: bool) -> pd.DataFrame:
    states = input_file_state(roles)
    rows = []
    for row in states.itertuples(index=False):
        observed = sha256_file(row.path) if hash_development else "not_rehashed"
        passed = observed == row.expected_sha256 if hash_development else True
        rows.append({**row._asdict(), "observed_sha256": observed, "hash_pass": passed})
    result = pd.DataFrame(rows)
    if not result["hash_pass"].all():
        failed = result.loc[~result["hash_pass"], "cohort_id"].tolist()
        raise RuntimeError(f"Input checksum mismatch: {failed}")
    return result


def _as_bool(frame: pd.DataFrame, column: str) -> np.ndarray:
    if column not in frame:
        return np.zeros(frame.shape[0], dtype=bool)
    values = frame[column]
    if pd.api.types.is_bool_dtype(values) or pd.api.types.is_numeric_dtype(values):
        return values.fillna(False).astype(bool).to_numpy()
    return values.astype("string").fillna("").str.lower().isin(["true", "1", "yes", "y", "t"]).to_numpy()


def build_development_obs(config: dict[str, Any], roles: pd.DataFrame) -> pd.DataFrame:
    label_manifest = pd.read_csv(
        resolve(config["inputs"]["v4_cell_label_manifest"]),
        usecols=["cell_id", "stage1_role", "nk_annotation_strength", "doublet_flag"],
        low_memory=False,
    )
    primary_nk_ids = set(
        label_manifest.loc[
            label_manifest["stage1_role"].eq("nk_negative")
            & label_manifest["nk_annotation_strength"].eq(1.0),
            "cell_id",
        ].astype(str)
    )
    productive_ids = set(label_manifest.loc[label_manifest["stage1_role"].eq("t_positive"), "cell_id"].astype(str))
    doublet_ids = set(label_manifest.loc[label_manifest["doublet_flag"].fillna(False).astype(bool), "cell_id"].astype(str))

    frames = []
    for role in roles.itertuples(index=False):
        frame = h5ad_obs_frame(role.path, OBS_COLUMNS)
        original = frame.index.astype(str)
        frame["input_row"] = np.arange(frame.shape[0], dtype=np.int64)
        frame["input_cohort_id"] = role.cohort_id
        frame["allow_pseudolabel_training"] = bool(role.allow_pseudolabel_training)
        if role.cohort_id == "current_atlas":
            if bool(getattr(role, "recovery_active", False)):
                recovery = config["current_atlas_recovery"]
                if frame.shape[0] != int(recovery["expected_raw_cells"]):
                    raise RuntimeError("Recovery source raw-cell count differs from the contract")
                frame["source_original_cell_id"] = frame["original_cell_id"].astype("string")
                excluded = recovery_excluded_cell_ids(config)
                remove = original.isin(excluded)
                if int(remove.sum()) != int(recovery["expected_intersecting_exclusions"]):
                    raise RuntimeError("Recovery source exclusion intersection differs from the contract")
                frame = frame.loc[~remove].copy()
                original = frame.index.astype(str)
                frame = attach_recovery_metadata(frame, config)
                if frame.shape[0] != int(recovery["expected_effective_cells"]):
                    raise RuntimeError("Recovery effective-cell count differs from the contract")
            frame["primary_nk_anchor"] = original.isin(primary_nk_ids)
            frame["productive_tcr_anchor"] = original.isin(productive_ids)
            frame["doublet_flag_effective"] = original.isin(doublet_ids)
        else:
            frame["primary_nk_anchor"] = False
            frame["productive_tcr_anchor"] = _as_bool(frame, "has_any_ab_tcr") | _as_bool(frame, "has_any_gd_tcr")
            frame["doublet_flag_effective"] = _as_bool(frame, "doublet_flag") | _as_bool(frame, "predicted_doublet")
        frame["candidate_eligible"] = (
            frame["allow_pseudolabel_training"].astype(bool)
            & ~frame["productive_tcr_anchor"].astype(bool)
            & ~frame["doublet_flag_effective"].astype(bool)
        )
        frame["original_cell_id"] = original
        frame.index = pd.Index(
            role.cohort_id + "::" + original,
            name="integration_cell_id",
        )
        frames.append(frame)
    obs = pd.concat(frames, axis=0, copy=False)
    if obs.index.duplicated().any():
        raise RuntimeError("Integration cell identifiers are not unique")
    batch = make_integration_batch(obs, config["staging"]["batch_key_hierarchy"])
    obs[batch.columns] = batch
    ensure_no_locked_cohorts(obs, validate_preflight_approval(config)["roles"])
    return obs


def select_hvgs(
    config: dict[str, Any], roles: pd.DataFrame, obs: pd.DataFrame, matrix_keys: dict[str, str]
) -> tuple[list[str], pd.DataFrame, pd.DataFrame]:
    gene_sets = [set(h5ad_var_names(row.path).tolist()) for row in roles.itertuples(index=False)]
    eligible = common_eligible_genes(gene_sets)
    hvg_cfg = config["hvg"]
    if len(eligible) < int(hvg_cfg["n_top_genes"]):
        raise RuntimeError("Eligible common-gene universe is smaller than the requested HVG count")
    sampled_global = source_balanced_sample_indices(
        obs["source_gse_id"].astype(str).to_numpy(),
        int(hvg_cfg["sample_cap_per_source"]),
        int(config["random_seed"]),
    )
    sample_obs = obs.iloc[sampled_global].copy()
    blocks = []
    ordered_sample_obs = []
    for role in roles.itertuples(index=False):
        subset = sample_obs[sample_obs["input_cohort_id"].eq(role.cohort_id)].sort_values("input_row")
        blocks.append(
            read_sparse_rows_genes(
                role.path,
                matrix_keys.get(role.cohort_id, matrix_keys["default"]),
                eligible,
                rows=subset["input_row"].to_numpy(np.int64),
                row_chunk_size=int(config["staging"]["row_chunk_size"]),
            )
        )
        ordered_sample_obs.append(subset)
    sample_obs = pd.concat(ordered_sample_obs, axis=0, copy=False)
    sample_matrix = sparse.vstack(blocks, format="csr", dtype=np.float32)
    if sample_matrix.shape[0] != sample_obs.shape[0]:
        raise RuntimeError("HVG sample matrix and metadata are misaligned")
    sample_adata = ad.AnnData(
        X=sample_matrix,
        obs=pd.DataFrame({hvg_cfg["batch_key"]: sample_obs[hvg_cfg["batch_key"]].astype(str).to_numpy()}, index=sample_obs.index),
        var=pd.DataFrame(index=pd.Index(eligible, name="gene")),
    )
    sc.pp.highly_variable_genes(
        sample_adata,
        flavor=hvg_cfg["flavor"],
        n_top_genes=int(hvg_cfg["n_top_genes"]),
        batch_key=hvg_cfg["batch_key"],
        subset=False,
        inplace=True,
    )
    selected = sample_adata.var.index[sample_adata.var["highly_variable"]].astype(str).tolist()
    if len(selected) != int(hvg_cfg["n_top_genes"]):
        raise RuntimeError(f"Expected {hvg_cfg['n_top_genes']} HVGs, observed {len(selected)}")
    if any(gene not in eligible for gene in selected):
        raise RuntimeError("An excluded gene entered the HVG set")
    hvg_table = sample_adata.var.reset_index()
    source_sample = sample_obs.groupby("source_gse_id", observed=True).size().rename("n_sampled").reset_index()
    del sample_adata, sample_matrix, blocks
    gc.collect()
    return selected, hvg_table, source_sample


def atomic_write_h5ad(adata: ad.AnnData, path: Path, compression: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".partial")
    temporary.unlink(missing_ok=True)
    adata.write_h5ad(temporary, compression=compression)
    temporary.replace(path)


def prepare_stage(config: dict[str, Any], paths: dict[str, Path], overwrite: bool) -> dict[str, Any]:
    if paths["staged_h5ad"].exists() and not overwrite:
        raise FileExistsError(f"Staged object exists: {paths['staged_h5ad']}")
    roles = development_roles(config)
    before = verify_input_contract(roles, hash_development=True)
    preflight_config = read_json(config["preflight"]["config"])
    matrix_keys = preflight_config["matrix_keys"]
    obs = build_development_obs(config, roles)
    selected, hvg_table, source_sample = select_hvgs(config, roles, obs, matrix_keys)

    blocks = []
    ordered_obs = []
    for role in roles.itertuples(index=False):
        subset = obs[obs["input_cohort_id"].eq(role.cohort_id)].sort_values("input_row")
        blocks.append(
            read_sparse_rows_genes(
                role.path,
                matrix_keys.get(role.cohort_id, matrix_keys["default"]),
                selected,
                rows=subset["input_row"].to_numpy(np.int64),
                row_chunk_size=int(config["staging"]["row_chunk_size"]),
            )
        )
        ordered_obs.append(subset)
    obs = pd.concat(ordered_obs, axis=0, copy=False)
    counts = sparse.vstack(blocks, format="csr", dtype=np.float32)
    if counts.shape != (obs.shape[0], len(selected)):
        raise RuntimeError("Staged count matrix and metadata have inconsistent dimensions")
    ensure_no_locked_cohorts(obs, validate_preflight_approval(config)["roles"])
    keep_obs = [
        "original_cell_id", "input_cohort_id", "input_row", "source_gse_id", "donor_id", "sample_id",
        "library_id", "technology_simple", "integration_batch", "integration_batch_level",
        "primary_nk_anchor", "productive_tcr_anchor", "doublet_flag_effective",
        "allow_pseudolabel_training", "candidate_eligible",
    ]
    staged_obs = obs[keep_obs].copy()
    for column in [
        "input_cohort_id", "source_gse_id", "donor_id", "sample_id", "library_id", "technology_simple",
        "integration_batch", "integration_batch_level",
    ]:
        staged_obs[column] = pd.Categorical(staged_obs[column].astype("string").fillna(""))
    var = hvg_table.set_index("gene").loc[selected].copy()
    adata = ad.AnnData(X=counts, obs=staged_obs, var=var)
    adata.uns["gdtai_v4_2_contract"] = {
        "protocol_version": config["protocol_version"],
        "execution_config_sha256": sha256_file(DEFAULT_CONFIG if DEFAULT_CONFIG.exists() else "configs/models/gdtai/v4_2_integration_execution.json"),
        "cohort_role_contract_sha256": role_contract_sha256(validate_preflight_approval(config)["roles"]),
        "raw_counts": True,
        "locked_cohorts_included": False,
    }
    atomic_write_h5ad(adata, paths["staged_h5ad"], config["staging"]["compression"])
    hvg_table.to_csv(paths["table"] / "hvg_selection.csv", index=False)
    source_sample.to_csv(paths["table"] / "hvg_source_balanced_sample.csv", index=False)
    before.to_csv(paths["table"] / "development_input_contract.csv", index=False)
    after = input_file_state(roles)
    unchanged = before[["cohort_id", "size_bytes", "mtime_ns"]].merge(
        after[["cohort_id", "size_bytes", "mtime_ns"]], on="cohort_id", suffixes=("_before", "_after")
    )
    unchanged["unchanged"] = (
        unchanged["size_bytes_before"].eq(unchanged["size_bytes_after"])
        & unchanged["mtime_ns_before"].eq(unchanged["mtime_ns_after"])
    )
    unchanged.to_csv(paths["table"] / "development_input_file_state.csv", index=False)
    if not unchanged["unchanged"].all():
        raise RuntimeError("A source H5AD changed during staging")
    summary = {
        "stage": "prepare",
        "status": "PASS",
        "n_cells": int(adata.n_obs),
        "n_hvgs": int(adata.n_vars),
        "matrix_nnz": int(adata.X.nnz),
        "staged_h5ad": str(paths["staged_h5ad"]),
        "staged_h5ad_sha256": sha256_file(paths["staged_h5ad"]),
        "primary_nk_anchors": int(adata.obs["primary_nk_anchor"].sum()),
        "productive_tcr_anchors": int(adata.obs["productive_tcr_anchor"].sum()),
        "candidate_eligible": int(adata.obs["candidate_eligible"].sum()),
        "locked_cohorts_included": False,
    }
    atomic_write_json(paths["log"] / "prepare_summary.json", summary)
    return summary


def fit_stage(config: dict[str, Any], paths: dict[str, Path], overwrite: bool) -> dict[str, Any]:
    if paths["latent"].exists() and not overwrite:
        raise FileExistsError(f"Latent representation exists: {paths['latent']}")
    gpu = require_gpu(config)
    import scvi

    adata = ad.read_h5ad(paths["staged_h5ad"])
    ensure_no_locked_cohorts(adata.obs, validate_preflight_approval(config)["roles"])
    scvi.settings.seed = int(config["random_seed"])
    scvi.model.SCVI.setup_anndata(adata, batch_key="integration_batch")
    model = scvi.model.SCVI(
        adata,
        n_hidden=int(config["scvi"]["n_hidden"]),
        n_layers=int(config["scvi"]["n_layers"]),
        n_latent=int(config["scvi"]["n_latent"]),
        gene_likelihood=config["scvi"]["gene_likelihood"],
    )
    started = time.time()
    model.train(
        max_epochs=int(config["scvi"]["max_epochs"]),
        batch_size=int(config["scvi"]["batch_size"]),
        accelerator="gpu",
        devices=1,
        early_stopping=bool(config["scvi"]["early_stopping"]),
        early_stopping_patience=int(config["scvi"]["early_stopping_patience"]),
    )
    latent = model.get_latent_representation(batch_size=int(config["scvi"]["batch_size"]))
    if latent.shape != (adata.n_obs, int(config["scvi"]["n_latent"])):
        raise RuntimeError("scVI latent shape differs from the frozen contract")
    temporary = paths["latent"].with_name(paths["latent"].name + ".partial.npy")
    np.save(temporary, latent.astype(np.float32))
    temporary.replace(paths["latent"])
    if paths["model"].exists() and overwrite:
        shutil.rmtree(paths["model"])
    model.save(paths["model"], overwrite=overwrite, save_anndata=False)
    history = pd.DataFrame({key: np.ravel(value) for key, value in model.history.items() if np.asarray(value).ndim <= 2})
    history.to_csv(paths["table"] / "scvi_training_history.csv", index=False)
    summary = {
        "stage": "fit",
        "status": "PASS",
        "elapsed_seconds": time.time() - started,
        "n_cells": int(adata.n_obs),
        "n_latent": int(latent.shape[1]),
        "latent_sha256": sha256_file(paths["latent"]),
        "gpu": gpu,
        "cpu_fallback": False,
    }
    atomic_write_json(paths["log"] / "fit_summary.json", summary)
    return summary


def _labels_to_codes(values: pd.Series) -> np.ndarray:
    return pd.Categorical(values).codes.astype(np.int32)


def cluster_stage(config: dict[str, Any], paths: dict[str, Path], overwrite: bool) -> dict[str, Any]:
    if paths["partitions"].exists() and not overwrite:
        raise FileExistsError(f"Cluster partitions exist: {paths['partitions']}")
    gpu = require_gpu(config)
    import rapids_singlecell as rsc

    backed = ad.read_h5ad(paths["staged_h5ad"], backed="r")
    obs = backed.obs.copy()
    backed.file.close()
    ensure_no_locked_cohorts(obs, validate_preflight_approval(config)["roles"])
    latent = np.load(paths["latent"], mmap_mode="r")
    graph = ad.AnnData(X=sparse.csr_matrix((obs.shape[0], 1), dtype=np.float32), obs=obs)
    graph.obsm["X_scVI"] = np.asarray(latent)
    clustering = config["clustering"]
    global_cfg = clustering["global"]
    rsc.pp.neighbors(
        graph,
        n_neighbors=int(global_cfg["n_neighbors"]),
        use_rep="X_scVI",
        random_state=int(config["random_seed"]),
        algorithm=clustering["algorithm"],
        algorithm_kwds=clustering["algorithm_kwds"],
    )
    global_grid = iter_parameter_grid(global_cfg["resolutions"], global_cfg["seeds"])
    global_labels = np.empty((graph.n_obs, len(global_grid)), dtype=np.int32)
    global_names = []
    for index, (resolution, seed) in enumerate(global_grid):
        key = f"global_r{resolution:g}_s{seed}"
        rsc.tl.leiden(graph, resolution=resolution, random_state=seed, key_added=key)
        global_labels[:, index] = _labels_to_codes(graph.obs[key])
        global_names.append(key)

    boundary_cfg = clustering["boundary"]
    boundary_mask, mixed_runs = mixed_boundary_mask(
        global_labels,
        obs["primary_nk_anchor"].astype(bool).to_numpy(),
        obs["productive_tcr_anchor"].astype(bool).to_numpy(),
        int(boundary_cfg["minimum_global_mixed_runs"]),
    )
    boundary_indices = np.flatnonzero(boundary_mask)
    if boundary_indices.size <= int(boundary_cfg["n_neighbors"]):
        raise RuntimeError("The expression-independent T/NK boundary is too small to recluster")
    boundary = ad.AnnData(
        X=sparse.csr_matrix((boundary_indices.size, 1), dtype=np.float32),
        obs=obs.iloc[boundary_indices].copy(),
    )
    boundary.obsm["X_scVI"] = np.asarray(latent[boundary_indices])
    rsc.pp.neighbors(
        boundary,
        n_neighbors=int(boundary_cfg["n_neighbors"]),
        use_rep="X_scVI",
        random_state=int(config["random_seed"]),
        algorithm=clustering["algorithm"],
        algorithm_kwds=clustering["algorithm_kwds"],
    )
    boundary_grid = iter_parameter_grid(boundary_cfg["resolutions"], boundary_cfg["seeds"])
    boundary_labels = np.empty((boundary.n_obs, len(boundary_grid)), dtype=np.int32)
    boundary_names = []
    for index, (resolution, seed) in enumerate(boundary_grid):
        key = f"boundary_r{resolution:g}_s{seed}"
        rsc.tl.leiden(boundary, resolution=resolution, random_state=seed, key_added=key)
        boundary_labels[:, index] = _labels_to_codes(boundary.obs[key])
        boundary_names.append(key)
    temporary = paths["partitions"].with_name(paths["partitions"].name + ".partial.npz")
    np.savez_compressed(
        temporary,
        global_labels=global_labels,
        boundary_indices=boundary_indices.astype(np.int64),
        boundary_labels=boundary_labels,
        mixed_global_runs=mixed_runs,
        global_names=np.asarray(global_names),
        boundary_names=np.asarray(boundary_names),
    )
    temporary.replace(paths["partitions"])
    summary = {
        "stage": "cluster",
        "status": "PASS",
        "n_cells": int(obs.shape[0]),
        "n_global_runs": len(global_names),
        "n_boundary_cells": int(boundary_indices.size),
        "n_boundary_runs": len(boundary_names),
        "partitions_sha256": sha256_file(paths["partitions"]),
        "gpu": gpu,
        "cpu_fallback": False,
    }
    atomic_write_json(paths["log"] / "cluster_summary.json", summary)
    return summary


def consensus_stage(config: dict[str, Any], paths: dict[str, Path]) -> dict[str, Any]:
    validate_pseudolabel_contract(config["pseudolabel"])
    backed = ad.read_h5ad(paths["staged_h5ad"], backed="r")
    obs = backed.obs.copy()
    backed.file.close()
    ensure_no_locked_cohorts(obs, validate_preflight_approval(config)["roles"])
    saved = np.load(paths["partitions"], allow_pickle=False)
    global_labels = saved["global_labels"]
    boundary_indices = saved["boundary_indices"]
    boundary_labels = saved["boundary_labels"]
    combined = np.full((obs.shape[0], global_labels.shape[1] + boundary_labels.shape[1]), -1, dtype=np.int32)
    combined[:, : global_labels.shape[1]] = global_labels
    combined[boundary_indices, global_labels.shape[1] :] = boundary_labels
    run_names = saved["global_names"].astype(str).tolist() + saved["boundary_names"].astype(str).tolist()
    cell, clusters = cluster_consensus_votes(
        combined,
        obs["primary_nk_anchor"].astype(bool).to_numpy(),
        obs["productive_tcr_anchor"].astype(bool).to_numpy(),
        obs["candidate_eligible"].astype(bool).to_numpy(),
        obs["source_gse_id"].astype(str).to_numpy(),
        config["pseudolabel"],
        run_names,
    )
    cell.index = obs.index
    selected = cell[cell["selected_pseudo_nk"]].join(
        obs[["original_cell_id", "input_cohort_id", "source_gse_id"]]
    )
    selected.to_csv(paths["table"] / "selected_pseudo_nk_cells.csv.gz", compression="gzip")
    clusters.to_csv(paths["table"] / "cluster_consensus_evidence.csv.gz", index=False, compression="gzip")
    by_source = (
        cell.join(obs[["source_gse_id"]])
        .groupby("source_gse_id", observed=True)
        .agg(
            n_candidate_eligible=("candidate_eligible", "sum"),
            n_selected_pseudo_nk=("selected_pseudo_nk", "sum"),
            mean_run_agreement=("run_agreement", "mean"),
        )
        .reset_index()
    )
    by_source.to_csv(paths["table"] / "pseudo_nk_counts_by_source.csv", index=False)
    primary_nk_n = int(obs["primary_nk_anchor"].sum())
    maximum_effective = primary_nk_n * float(config["pseudolabel"]["maximum_total_effective_weight_relative_to_primary_nk"])
    raw_effective = selected.shape[0] * float(config["pseudolabel"]["reliability_weight"])
    summary = {
        "stage": "consensus",
        "status": "PASS",
        "n_candidate_eligible": int(cell["candidate_eligible"].sum()),
        "n_selected_pseudo_nk": int(selected.shape[0]),
        "raw_pseudo_nk_effective_weight": raw_effective,
        "maximum_allowed_effective_weight": maximum_effective,
        "classifier_stage_must_source_balance_and_cap": bool(raw_effective > maximum_effective),
        "marker_thresholds_used_for_truth": False,
        "locked_cohorts_included": False,
    }
    atomic_write_json(paths["log"] / "consensus_summary.json", summary)
    return summary


def main() -> None:
    args = parse_args()
    config_path = resolve(args.config)
    config = read_json(config_path)
    preflight = validate_preflight_approval(config)
    recovery = validate_recovery_preflight(config)
    resource = validate_resource_preflight(config)
    paths = stage_paths(config)
    validation = {
        "status": "PASS",
        "protocol_version": config["protocol_version"],
        "preflight_protocol_version": preflight["protocol_version"],
        "execution_config_sha256": sha256_file(config_path),
        "runner_sha256": sha256_file(RUNNER_PATH),
        "core_sha256": sha256_file(CORE_PATH),
        "development_cohorts": int(preflight["roles"]["include_in_integration_fit"].sum()),
        "locked_cohorts": int(preflight["roles"]["allow_locked_evaluation"].sum()),
        "current_atlas_recovery_active": bool(recovery.get("active", True)),
        "recovery_contract_sha256": recovery.get("recovery_contract_sha256"),
        "resource_contract_sha256": resource.get("resource_contract_sha256"),
    }
    if args.stage == "validate":
        print(json.dumps(validation, indent=2, sort_keys=True))
        return

    validate_project_data_approval(config_path, config, RUNNER_PATH, CORE_PATH)
    stages = [args.stage] if args.stage != "all" else ["prepare", "fit", "cluster", "consensus"]
    results: dict[str, Any] = {"validation": validation}
    for stage in stages:
        results[f"{stage}_resources"] = ensure_resources(config, paths, stage)
        if stage == "prepare":
            results[stage] = prepare_stage(config, paths, args.overwrite)
        elif stage == "fit":
            results[stage] = fit_stage(config, paths, args.overwrite)
        elif stage == "cluster":
            results[stage] = cluster_stage(config, paths, args.overwrite)
        elif stage == "consensus":
            results[stage] = consensus_stage(config, paths)
        else:
            raise AssertionError(stage)
        print(json.dumps(results[stage], indent=2, sort_keys=True))
    atomic_write_json(paths["log"] / "run_summary.json", results)


if __name__ == "__main__":
    main()
